//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activ.Pointis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employes()
        {
            this.Pointage = new List<Pointage>();
            this.Responsable1 = new List<Responsable>();
            this.Responsable2 = new List<Responsable>();
        }
    
        public long EmployeID { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Sexe { get; set; }
        public long SocieteID { get; set; }
        public string Titre { get; set; }
        public string Matricule { get; set; }
        public long EquipeID { get; set; }
        public string Password { get; set; }
        public string Responsable { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> DateGenerationBadge { get; set; }
        public Nullable<System.DateTime> UserGenerate { get; set; }
        public string Support { get; set; }
    
        public  EquipeTravail EquipeTravail { get; set; }
        public  Societe Societe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<Pointage> Pointage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<Responsable> Responsable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<Responsable> Responsable2 { get; set; }
    }
}
