//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activ.Pointis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsable
    {
        public long ID { get; set; }
        public long EmployesID { get; set; }
        public long ResponsableID { get; set; }
    
        public  Employes Employes { get; set; }
        public  Employes Employes1 { get; set; }
    }
}
