//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activ.Pointis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteTravail
    {
        public long ID { get; set; }
        public long SocieteID { get; set; }
        public string Commune { get; set; }
        public string Ville { get; set; }
        public string CoordonnerGPS { get; set; }
        public string Quartier { get; set; }
        public string Pays { get; set; }
        public string Libelle { get; set; }
    
        public Societe Societe { get; set; }
    }
}
